databaseType = "PostgreSql"
id = "f2544084-04c5-4d5f-9f67-82ac398037fc"
name = "UBS ExpenseManager"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.UBSExpenseManagerDev]
url = "jdbc:postgresql://35.198.43.149:5432/ubs-expensemanager-dev"
schemas = [ "public" ]
