spring.application.name=ExpenseManager
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_manager
spring.datasource.username=expense_user
spring.datasource.password=expense_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration