services:
  backend:
    restart: always
    
    environment:
      SPRING_PROFILES_ACTIVE: prod
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
